# Generated by Django 3.2.9 on 2022-02-15 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_manage_book', '書籍編集権限'),)},
        ),
    ]
